"""auto-vote

Revision ID: 869f360cc58b
Revises: 9ffd7bbf6547
Create Date: 2025-10-12 13:02:31.757370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '869f360cc58b'
down_revision: Union[str, None] = '9ffd7bbf6547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    # op.alter_column('users', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=True,
    #            existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('users', 'created_at',
    #            existing_type=postgresql.TIMESTAMP(timezone=True),
    #            nullable=False,
    #            existing_server_default=sa.text('now()'))
    op.drop_table('votes')
    # ### end Alembic commands ###
